home_feed:
    path: /{page}
    defaults: { _controller: AppBundle:Home:feed, page: 1}
    requirements:
        page: '\d+'

post_show:
    path: /post/{id}/
    defaults: { _controller: AppBundle:Post:show }
    requirements:
      id: '\d+'

post_new:
    path: /post/new
    defaults: { _controller: AppBundle:Post:new }

post_edit:
    path: /post/{id}/edit
    defaults: { _controller: AppBundle:Post:edit }
    requirements:
      id: '\d+'